# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python -m pip install --user --upgrade setuptools wheel
      
      - run:
          name: setup
          command: |
            python setup.py sdist bdist_wheel

      - run:
          name: install twine
          command: |
            python -m pip install --user --upgrade twine
  
      - run:
          name: setup enviroment
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload
          command: |
            #!/bin/bash
            twine upload dist/*
